### ISSUE TITLE
Docker-compose installation: cannot use a container name other than 'search' for elasticseach

### ISSUE THREAD

**Issue by TKivai** [FusionAuth/fusionauth-site#1649]
When doing a local installation of fusionauth in the [Docker Compose installation](https://fusionauth.io/docs/v1/tech/installation-guide/docker#docker-compose), the elasticsearch container name has to be named '**search**' and consequently when defining the search servers, the url has to be 'http://**search**:9200'.

I tried changing the elasticsearch container name to a more descriptive '**fusionauth_search**' and also changed the search servers url to 'http://**fusionauth_search**:9200' but the fusionauth server could not start up.It had gone into silent mode. On inspecting the logs it seemed that fusionauth could not connect to the elasticsearch container using its container name.

`2022-10-07 09:18:12.706 AM INFO  com.inversoft.maintenance.search.ElasticsearchSilentModeWorkflowTask - Attempt 2 of 100. Waiting for search to become available [SERVER_DOWN]. Error [http://fusionauth_search:9200]`

To troubleshoot I got into the container, installed curl and tried accessing elasticsearch using the command `curl http://fusionauth_search:9200` and it worked. I am not sure why in the container, the curl command could access elasticsearch but the fusionauth server could not access it.

This may or may not be a bug but if there is a reason for this behavior it would be very helpful if it was included in the documentation.

**Comment by mooreds** [comment]
@TKivai can you share your entire docker compose file and your .env file? That will help us replicate and determine if this is a bug or not.

**Comment by TKivai** [comment]
##    .env file
```
FUSIONAUTH_POSTGRES_USER=postgres
FUSIONAUTH_POSTGRES_PASSWORD=postgres
FUSIONAUTH_DB_PORT=5432
FUSIONAUTH_DATABASE_USERNAME=fusionauth
FUSIONAUTH_DATABASE_PASSWORD=hkaLBM3RVnyYeYeqE3WI1w2e4Avpy0Wd5O3s3
FUSIONAUTH_ES_JAVA_OPTS="-Xms512m -Xmx512m"
FUSIONAUTH_APP_MEMORY=512M

FUSIONAUTH_MAILDEV_SMTP_SERVER_PORT=1025
FUSIONAUTH_MAILDEV_CLIENT_PORT=1080
```

## docker-compose.yml file

```
version: "3"

services:
  # FUSIONAUTH SERVICES
  fusionauth_db:
    image: postgres:14.5
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${FUSIONAUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FUSIONAUTH_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - fusionauth_db_net
    volumes:
      - fusionauth_db_data:/var/lib/postgresql/data

  fusionauth_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: fusionauth_search
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: ${FUSIONAUTH_ES_JAVA_OPTS}
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - fusionauth_elasticsearch_net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - fusionauth_elasticsearch_data:/usr/share/elasticsearch/data

  # fusionauth_maildev:
  #   image: maildev/maildev:2.0.5
  #   ports:
  #     - "${FUSIONAUTH_MAILDEV_SMTP_SERVER_PORT}:1025"
  #     - "${FUSIONAUTH_MAILDEV_CLIENT_PORT}:1080"
  #   networks:
  #     - fusionauth_maildev_net

  fusionauth:
    image: fusionauth/fusionauth-app:1.40.2
    depends_on:
      fusionauth_db:
        condition: service_healthy
      fusionauth_elasticsearch:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://fusionauth_db:${FUSIONAUTH_DB_PORT}/fusionauth
      DATABASE_ROOT_USERNAME: ${FUSIONAUTH_POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${FUSIONAUTH_POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${FUSIONAUTH_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${FUSIONAUTH_DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_SERVERS: http://fusionauth_search:9200
      SEARCH_TYPE: elasticsearch

    networks:
      - fusionauth_db_net
      - fusionauth_elasticsearch_net
      # - fusionauth_maildev_net
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config

networks:
  fusionauth_db_net:
    driver: bridge
  fusionauth_elasticsearch_net:
    driver: bridge
  # fusionauth_maildev_net:
  #   driver: bridge

volumes:
  fusionauth_db_data:
  fusionauth_config:
  fusionauth_elasticsearch_data:

```

**Comment by mooreds** [comment]
hi @TKivai ,

I was not able to recreate. To use a different search server, I needed to change the container name and the `SEARCH_SERVERS` env variable.

Here's my docker-compose file.

```
version: '3'

services:
  db:
    image: postgres:12.9
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_net
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  search2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: search2
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - search_net
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - search_data:/usr/share/elasticsearch/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      db:
        condition: service_healthy
      search2:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_SERVERS: http://search2:9200
      SEARCH_TYPE: elasticsearch

    networks:
      - db_net
      - search_net
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config

networks:
  db_net:
    driver: bridge
  search_net:
    driver: bridge

volumes:
  db_data:
  fusionauth_config:
  search_data:
```

And here's my .env file:

```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
DATABASE_USERNAME=fusionauth
DATABASE_PASSWORD=hkaLBM3RVnyYeYeqE3WI1w2e4Avpy0Wd5O3s3
ES_JAVA_OPTS="-Xms512m -Xmx512m"
FUSIONAUTH_APP_MEMORY=512M
```

Can you please try the files I provided?
